name: 'Matify'
description: 'Mattermost Notification for Github Actions'
author: 'tferreira'
inputs:
  type:
    description: 'job status (success or failure)'
    required: true
  job_name:
    description: 'job name of workflow (format: markdown)'
    required: true
  username:
    description: 'mattermost username'
    required: false
    default: 'Github Actions'
  icon_emoji:
    description: 'mattermost icon emoji'
    required: false
    default: 'github'
  channel:
    description: 'mattermost channel'
    required: false
  url:
    description: 'mattermost incoming webhook url'
    required: false
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'bell'
  color: 'green'